# Generated by Django 5.2.10 on 2026-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('message', models.TextField(help_text='Alert message details')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Alert severity level', max_length=20)),
                ('alert_type', models.CharField(choices=[('temperature', 'High Temperature'), ('humidity', 'High Humidity'), ('wind', 'High Wind Speed'), ('rain', 'Heavy Rain'), ('cold', 'Cold Weather')], default='temperature', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this alert')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether user has dismissed this alert')),
                ('location', models.CharField(help_text='Location of the alert', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
