# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(help_text='User who received this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', '-timestamp'], name='alerts_aler_user_id_4fdf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'),
        ),
    ]
