# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the statistics')),
                ('avg_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('max_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('min_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('avg_humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weather_condition', models.CharField(max_length=50)),
                ('precipitation_chance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Weather Stats',
                'verbose_name_plural': 'Daily Weather Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temperature', models.FloatField(default=25.0, help_text="Average temperature in user's location", validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('max_temperature', models.FloatField(default=35.0, help_text='Maximum temperature recorded', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('min_temperature', models.FloatField(default=15.0, help_text='Minimum temperature recorded', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('avg_humidity', models.IntegerField(default=65, help_text='Average humidity percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_humidity', models.IntegerField(default=95, help_text='Maximum humidity recorded', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_humidity', models.IntegerField(default=30, help_text='Minimum humidity recorded', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_wind_speed', models.FloatField(default=12.0, help_text='Average wind speed in km/h', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_wind_speed', models.FloatField(default=40.0, help_text='Maximum wind speed recorded', validators=[django.core.validators.MinValueValidator(0)])),
                ('rainy_days_count', models.IntegerField(default=0, help_text='Number of rainy days recorded', validators=[django.core.validators.MinValueValidator(0)])),
                ('sunny_days_count', models.IntegerField(default=0, help_text='Number of sunny days recorded', validators=[django.core.validators.MinValueValidator(0)])),
                ('cloudy_days_count', models.IntegerField(default=0, help_text='Number of cloudy days recorded', validators=[django.core.validators.MinValueValidator(0)])),
                ('alerts_triggered', models.IntegerField(default=0, help_text='Number of alerts triggered for this user', validators=[django.core.validators.MinValueValidator(0)])),
                ('alerts_read', models.IntegerField(default=0, help_text='Number of alerts read by user', validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_chats_initiated', models.IntegerField(default=0, help_text='Number of AI chat conversations started', validators=[django.core.validators.MinValueValidator(0)])),
                ('news_articles_read', models.IntegerField(default=0, help_text='Number of news articles read', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_alert_time', models.DateTimeField(blank=True, help_text='When the last alert was triggered', null=True)),
                ('last_check_time', models.DateTimeField(blank=True, help_text='Last time user checked weather', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
            },
        ),
    ]
