# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweatherstats',
            name='user',
            field=models.ForeignKey(help_text='User associated with these stats', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='users.user'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(help_text="User whose analytics we're tracking", on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyweatherstats',
            unique_together={('user', 'date')},
        ),
    ]
