"""
Comprehensive News Channels Database
Structure: Country -> States -> Official News Channels
Each channel includes official streaming/website URLs with priority ranking
"""

NEWS_CHANNELS_DATA = {
    "India": {
        "Tamil Nadu": [
            {
                "name": "Sun News",
                "language": "Tamil",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Tamil Nadu",
                "official_website": "https://www.sunnewsgroup.com/",
                "embed_url": None,  # Will try to detect
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@SunNews",
                "logo_url": "https://www.sunnewsgroup.com/logo.png",
                "is_official": True,
                "priority": 1,
                "fallback_level": "state"
            },
            {
                "name": "Thanthi TV",
                "language": "Tamil",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Tamil Nadu",
                "official_website": "https://www.thanthitv.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@ThanthiTV",
                "logo_url": "https://www.thanthitv.com/logo.png",
                "is_official": True,
                "priority": 2,
                "fallback_level": "state"
            },
            {
                "name": "News7 Tamil",
                "language": "Tamil",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Tamil Nadu",
                "official_website": "https://www.news7.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@News7Tamil",
                "logo_url": "https://www.news7.com/logo.png",
                "is_official": True,
                "priority": 3,
                "fallback_level": "state"
            },
            {
                "name": "Puthiya Thalaimurai",
                "language": "Tamil",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Tamil Nadu",
                "official_website": "https://www.puthiyathalaimurai.tv/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@PuthiyaThalaimurai",
                "logo_url": "https://www.puthiyathalaimurai.tv/logo.png",
                "is_official": True,
                "priority": 4,
                "fallback_level": "state"
            }
        ],
        "Karnataka": [
            {
                "name": "Udaya News",
                "language": "Kannada",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Karnataka",
                "official_website": "https://www.udaynews.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@UdayNews",
                "logo_url": "https://www.udaynews.com/logo.png",
                "is_official": True,
                "priority": 1,
                "fallback_level": "state"
            },
            {
                "name": "Janasri News",
                "language": "Kannada",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Karnataka",
                "official_website": "https://www.janasrinews.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@JanasriNews",
                "logo_url": "https://www.janasrinews.com/logo.png",
                "is_official": True,
                "priority": 2,
                "fallback_level": "state"
            },
            {
                "name": "TV5 Kannada",
                "language": "Kannada",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Karnataka",
                "official_website": "https://www.tv5kannada.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@TV5Kannada",
                "logo_url": "https://www.tv5kannada.com/logo.png",
                "is_official": True,
                "priority": 3,
                "fallback_level": "state"
            },
            {
                "name": "Namma TV",
                "language": "Kannada",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Karnataka",
                "official_website": "https://www.nammatv.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@NammaTV",
                "logo_url": "https://www.nammatv.com/logo.png",
                "is_official": True,
                "priority": 4,
                "fallback_level": "state"
            }
        ],
        "Telangana": [
            {
                "name": "Eenadu News",
                "language": "Telugu",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Telangana",
                "official_website": "https://www.eenadu.net/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@EenadyTeluguNews",
                "logo_url": "https://www.eenadu.net/logo.png",
                "is_official": True,
                "priority": 1,
                "fallback_level": "state"
            },
            {
                "name": "Andhra Jyothi",
                "language": "Telugu",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Telangana",
                "official_website": "https://www.andrajyothi.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@AndraJyothi",
                "logo_url": "https://www.andrajyothi.com/logo.png",
                "is_official": True,
                "priority": 2,
                "fallback_level": "state"
            },
            {
                "name": "Sakshi TV",
                "language": "Telugu",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Telangana",
                "official_website": "https://www.sakshitv.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@SakshiTV",
                "logo_url": "https://www.sakshitv.com/logo.png",
                "is_official": True,
                "priority": 3,
                "fallback_level": "state"
            },
            {
                "name": "TV9 Telangana",
                "language": "Telugu",
                "channel_type": "news",
                "category": "general",
                "country": "India",
                "state": "Telangana",
                "official_website": "https://www.tv9telugu.com/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@TV9Telugu",
                "logo_url": "https://www.tv9telugu.com/logo.png",
                "is_official": True,
                "priority": 4,
                "fallback_level": "state"
            }
        ]
    },
    "USA": {
        "California": [
            {
                "name": "NBC Bay Area",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "California",
                "official_website": "https://www.nbcbayarea.com/",
                "embed_url": None,
                "rss_url": "https://www.nbcbayarea.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@NBCBayArea",
                "logo_url": "https://www.nbcbayarea.com/logo.png",
                "is_official": True,
                "priority": 1,
                "fallback_level": "state"
            },
            {
                "name": "KTVU FOX 2",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "California",
                "official_website": "https://www.ktvu.com/",
                "embed_url": None,
                "rss_url": "https://www.ktvu.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@KTVU",
                "logo_url": "https://www.ktvu.com/logo.png",
                "is_official": True,
                "priority": 2,
                "fallback_level": "state"
            },
            {
                "name": "ABC7 News Bay Area",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "California",
                "official_website": "https://abc7news.com/",
                "embed_url": None,
                "rss_url": "https://abc7news.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@ABC7NewsBA",
                "logo_url": "https://abc7news.com/logo.png",
                "is_official": True,
                "priority": 3,
                "fallback_level": "state"
            },
            {
                "name": "CBS Bay Area",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "California",
                "official_website": "https://www.cbsnews.com/bayarea/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@CBSBayArea",
                "logo_url": "https://www.cbsnews.com/logo.png",
                "is_official": True,
                "priority": 4,
                "fallback_level": "state"
            }
        ],
        "New York": [
            {
                "name": "NY1 News",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "New York",
                "official_website": "https://www.ny1.com/",
                "embed_url": None,
                "rss_url": "https://www.ny1.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@NY1News",
                "logo_url": "https://www.ny1.com/logo.png",
                "is_official": True,
                "priority": 1,
                "fallback_level": "state"
            },
            {
                "name": "NBC New York",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "New York",
                "official_website": "https://www.nbcnewyork.com/",
                "embed_url": None,
                "rss_url": "https://www.nbcnewyork.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@NBCNewYork",
                "logo_url": "https://www.nbcnewyork.com/logo.png",
                "is_official": True,
                "priority": 2,
                "fallback_level": "state"
            },
            {
                "name": "ABC7 New York",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "New York",
                "official_website": "https://abc7ny.com/",
                "embed_url": None,
                "rss_url": "https://abc7ny.com/feeds/",
                "youtube_channel": "https://www.youtube.com/@ABC7NewYork",
                "logo_url": "https://abc7ny.com/logo.png",
                "is_official": True,
                "priority": 3,
                "fallback_level": "state"
            },
            {
                "name": "CBS New York",
                "language": "English",
                "channel_type": "news",
                "category": "general",
                "country": "USA",
                "state": "New York",
                "official_website": "https://www.cbsnews.com/newyork/",
                "embed_url": None,
                "rss_url": None,
                "youtube_channel": "https://www.youtube.com/@CBSNewYork",
                "logo_url": "https://www.cbsnews.com/logo.png",
                "is_official": True,
                "priority": 4,
                "fallback_level": "state"
            }
        ]
    }
}

# Country-level fallback sources (if state doesn't have 4 channels)
COUNTRY_FALLBACK_SOURCES = {
    "India": [
        {
            "name": "NDTV India",
            "language": "English",
            "channel_type": "news",
            "category": "general",
            "country": "India",
            "state": None,
            "official_website": "https://www.ndtvindia.com/",
            "embed_url": None,
            "rss_url": "https://www.ndtvindia.com/feeds/",
            "youtube_channel": "https://www.youtube.com/@NDTV",
            "logo_url": "https://www.ndtvindia.com/logo.png",
            "is_official": True,
            "priority": 5,
            "fallback_level": "country"
        },
        {
            "name": "India Today",
            "language": "English",
            "channel_type": "news",
            "category": "general",
            "country": "India",
            "state": None,
            "official_website": "https://www.indiatoday.in/",
            "embed_url": None,
            "rss_url": "https://www.indiatoday.in/feeds/",
            "youtube_channel": "https://www.youtube.com/@IndiaToday",
            "logo_url": "https://www.indiatoday.in/logo.png",
            "is_official": True,
            "priority": 6,
            "fallback_level": "country"
        }
    ],
    "USA": [
        {
            "name": "CNN",
            "language": "English",
            "channel_type": "news",
            "category": "general",
            "country": "USA",
            "state": None,
            "official_website": "https://www.cnn.com/",
            "embed_url": None,
            "rss_url": "https://www.cnn.com/feeds/",
            "youtube_channel": "https://www.youtube.com/@CNN",
            "logo_url": "https://www.cnn.com/logo.png",
            "is_official": True,
            "priority": 5,
            "fallback_level": "country"
        },
        {
            "name": "BBC News",
            "language": "English",
            "channel_type": "news",
            "category": "general",
            "country": "USA",
            "state": None,
            "official_website": "https://www.bbc.com/news/",
            "embed_url": None,
            "rss_url": "https://www.bbc.com/news/feeds/",
            "youtube_channel": "https://www.youtube.com/@BBCNews",
            "logo_url": "https://www.bbc.com/logo.png",
            "is_official": True,
            "priority": 6,
            "fallback_level": "country"
        }
    ]
}
