# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News article title', max_length=300)),
                ('slug', models.SlugField(help_text='URL slug for the article', max_length=300, unique=True)),
                ('content', models.TextField(help_text='Full article content')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the article', max_length=500)),
                ('source', models.CharField(choices=[('weather_service', 'National Weather Service'), ('climate_research', 'Climate Research Center'), ('local_news', 'Local News'), ('internal', 'Internal')], default='internal', help_text='Source of the news', max_length=50)),
                ('source_url', models.URLField(blank=True, help_text='Original source URL if external', null=True)),
                ('category', models.CharField(choices=[('forecasts', 'Weather Forecasts'), ('climate', 'Climate & Research'), ('general', 'General News'), ('alerts', 'Weather Alerts'), ('tips', 'Weather Tips')], default='general', help_text='News category', max_length=50)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='news/images/')),
                ('author', models.CharField(default='WeatherHub Team', help_text='Article author', max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether article is published')),
                ('views_count', models.IntegerField(default=0, help_text='Number of views')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='news_news_publish_3e11bb_idx'), models.Index(fields=['category'], name='news_news_categor_05ff13_idx'), models.Index(fields=['is_published'], name='news_news_is_publ_075179_idx')],
            },
        ),
    ]
