# Generated by Django 5.2.10 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Channel name (e.g., Sun News)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('language', models.CharField(help_text='Primary language (e.g., Tamil, English, Hindi)', max_length=50)),
                ('channel_type', models.CharField(choices=[('news', 'News'), ('weather', 'Weather'), ('sports', 'Sports'), ('business', 'Business'), ('entertainment', 'Entertainment')], default='news', help_text='Type of channel', max_length=20)),
                ('country', models.CharField(help_text='Country (e.g., India, USA)', max_length=100)),
                ('state', models.CharField(help_text='State/Region (e.g., Tamil Nadu, New York)', max_length=200)),
                ('city', models.CharField(blank=True, help_text='City (optional)', max_length=200)),
                ('stream_type', models.CharField(choices=[('youtube', 'YouTube Live'), ('official_website', 'Official Website'), ('streaming_platform', 'Streaming Platform'), ('direct_stream', 'Direct Stream URL'), ('website_link', 'Website Link')], default='youtube', help_text='Type of streaming source', max_length=30)),
                ('stream_url', models.URLField(help_text='Official streaming URL or YouTube embed link')),
                ('website_url', models.URLField(blank=True, help_text="Channel's official website")),
                ('youtube_channel', models.CharField(blank=True, help_text='YouTube channel ID or URL', max_length=255)),
                ('logo', models.URLField(blank=True, help_text='Channel logo URL')),
                ('thumbnail', models.URLField(blank=True, help_text='Channel thumbnail/cover image')),
                ('description', models.TextField(blank=True, help_text='Channel description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether channel is currently streaming')),
                ('is_verified', models.BooleanField(default=False, help_text='Official channel verified')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this channel was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Channel',
                'verbose_name_plural': 'News Channels',
                'ordering': ['country', 'state', 'name'],
                'indexes': [models.Index(fields=['country', 'state'], name='news_newsch_country_2160b6_idx'), models.Index(fields=['language'], name='news_newsch_languag_9cda42_idx'), models.Index(fields=['is_active'], name='news_newsch_is_acti_463826_idx')],
                'unique_together': {('country', 'state', 'name')},
            },
        ),
    ]
