# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('max_temperature', models.FloatField(help_text='Maximum temperature in Celsius')),
                ('min_temperature', models.FloatField(help_text='Minimum temperature in Celsius')),
                ('weather_condition', models.CharField(max_length=50)),
                ('humidity', models.IntegerField(help_text='Humidity in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h', validators=[django.core.validators.MinValueValidator(0)])),
                ('precipitation_chance', models.IntegerField(default=0, help_text='Chance of precipitation in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('humidity', models.IntegerField(help_text='Humidity in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h', validators=[django.core.validators.MinValueValidator(0)])),
                ('weather_condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Partly Cloudy', 'Partly Cloudy'), ('Windy', 'Windy'), ('Foggy', 'Foggy'), ('Thunderstorm', 'Thunderstorm')], default='Partly Cloudy', max_length=50)),
                ('feels_like', models.FloatField(blank=True, help_text='Feels like temperature in Celsius', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Visibility in km', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='weather_wea_locatio_819d67_idx')],
            },
        ),
    ]
