# Generated by Django 5.2.10 on 2026-02-06 04:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('location', models.CharField(choices=[('Chennai', 'Chennai, Tamil Nadu'), ('Velachery', 'Velachery, Chennai'), ('Anna Nagar', 'Anna Nagar, Chennai'), ('T. Nagar', 'T. Nagar, Chennai'), ('Adyar', 'Adyar, Chennai')], default='Chennai', max_length=100)),
                ('temperature_threshold', models.IntegerField(default=35, help_text='Temperature alert threshold in Celsius', validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)])),
                ('humidity_threshold', models.IntegerField(default=80, help_text='Humidity alert threshold in percentage', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('wind_speed_threshold', models.IntegerField(default=40, help_text='Wind speed alert threshold in km/h', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)])),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable/disable push notifications')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='weather_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='weather_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
