# Generated by Django 5.2.10 on 2026-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newschannel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_channels',
            field=models.ManyToManyField(blank=True, help_text="User's favorite news channels", related_name='favorited_by_users', to='news.newschannel'),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese')], default='en', help_text='Preferred language for news channels and interface', max_length=10),
        ),
    ]
